Added 'done' parameter to use default arguments
christianscott/curry.py pull request #16
Opened 2017-09-30 06:55 UTC by TechieBoy

For #11

2017-09-30 07:08 UTC, praveensvsrk commented
Why are you doing this?
```python
 if done_keyword in kwargs_store:
     done_evaluation = kwargs_store.pop(done_keyword,False)
```
What if the 'done' keyword is an **argument** of the function being curried?

2017-09-30 07:11 UTC, TechieBoy commented
We can change the argument name to something like "curry_done=True" to avoid such conflicts unless there is some way to distinguish whether the argument is for the original function or for the curried function.

2017-09-30 10:49 UTC, PaiAkshay998 commented
I think you need to also check for the case where you pass all the required arguments in one go along with the done=True condition. For example,
```python
def test_default_param2(self):
        @curry
        def add(a,b=10): 
            return a+b
        self.assertEqual(20,add(10,done=True))
```
Python should be throwing a TypeError for this case ( correct me if I'm wrong ). 
A possible fix for this is to add 
```python
if done_eval():
    return fun(*args_store, **kwargs_store)
```
immediately after your done_eval() definition.

2017-10-05 17:10 UTC, akspi requested changes

2017-10-05 17:10 UTC, PaiAkshay998 commented on curry.py
> +
You'll need this line of code after your function definition.
```python
if done_eval():
    return fun(*args_store, **kwargs_store)
```

2018-02-15 06:52 UTC, closed without merging